//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiFactor.SelfService.Windows.Portal.Resources.Home.ru", typeof(Home_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сменить пароль.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настроить 2FA.
        /// </summary>
        public static string Configure2FA {
            get {
                return ResourceManager.GetString("Configure2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас подключены следующие способы проверки доступа:.
        /// </summary>
        public static string ConfiguredMethods {
            get {
                return ResourceManager.GetString("ConfiguredMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждаете отключение?.
        /// </summary>
        public static string ConfirmRemoving {
            get {
                return ResourceManager.GetString("ConfirmRemoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравствуйте,.
        /// </summary>
        public static string Greetings {
            get {
                return ResourceManager.GetString("Greetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверить устройства с почтой.
        /// </summary>
        public static string ManageActiveSyncDevices {
            get {
                return ResourceManager.GetString("ManageActiveSyncDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мобильное приложение.
        /// </summary>
        public static string MobileApp {
            get {
                return ResourceManager.GetString("MobileApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Осталось дней.
        /// </summary>
        public static string PasswordExpirationDaysLeft {
            get {
                return ResourceManager.GetString("PasswordExpirationDaysLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to отключить.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключить мобильное приложение.
        /// </summary>
        public static string SetupMobileApp {
            get {
                return ResourceManager.GetString("SetupMobileApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключить Telegram.
        /// </summary>
        public static string SetupTelegram {
            get {
                return ResourceManager.GetString("SetupTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подключить Яндекс.Ключ.
        /// </summary>
        public static string SetupYandexKey {
            get {
                return ResourceManager.GetString("SetupYandexKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо изменить пароль!.
        /// </summary>
        public static string ShouldChangePassword {
            get {
                return ResourceManager.GetString("ShouldChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Яндекс.Ключ.
        /// </summary>
        public static string YandexKey {
            get {
                return ResourceManager.GetString("YandexKey", resourceCulture);
            }
        }
    }
}
